In [69]:
import pandas as pd
import numpy as np

In [70]:
data = {
'Department': ['IT', 'HR', 'IT', 'Finance', 'HR', 'Finance', 'IT'],
'Employee': ['A', 'B', 'C', 'D', 'E', 'F', 'G'],
'Salary': [50000, 40000, 55000, 60000, 42000, 65000, 58000],
'Experience': [2, 1, 3, 5, 2, 6, 4]
}


df = pd.DataFrame(data)
df

  Department Employee  Salary  Experience
0         IT        A   50000           2
1         HR        B   40000           1
2         IT        C   55000           3
3    Finance        D   60000           5
4         HR        E   42000           2
5    Finance        F   65000           6
6         IT        G   58000           4

3. What is GroupBy?

groupby() is used to split data into groups, apply a function, and combine results.

Split → Apply → Combine

Basic GroupBy (Single Column)
Group by Department

In [71]:
df.groupby('Department')

In [72]:
df.groupby('Department')['Salary'].mean()
#Calculate Mean Salary per Department

Department
Finance    62500.000000
HR         41000.000000
IT         54333.333333
Name: Salary, dtype: float64

In [73]:
# Multiple Aggregations
df.groupby('Department')['Salary'].agg(['mean', 'max', 'min', 'sum'])

                    mean    max    min     sum
Department
Finance     62500.000000  65000  60000  125000
HR          41000.000000  42000  40000   82000
IT          54333.333333  58000  50000  163000

In [74]:
# GroupBy with Multiple Columns
df.groupby(['Department', 'Experience'])['Salary'].mean()

Department  Experience
Finance     5             60000.0
            6             65000.0
HR          1             40000.0
            2             42000.0
IT          2             50000.0
            3             55000.0
            4             58000.0
Name: Salary, dtype: float64

In [75]:
df.groupby('Department')['Employee'].count()
#Using GroupBy with Count

Department
Finance    2
HR         2
IT         3
Name: Employee, dtype: int64

In [76]:
def salary_range(x):
 return x.max() - x.min()


df.groupby('Department')['Salary'].apply(salary_range)

Department
Finance    5000
HR         2000
IT         8000
Name: Salary, dtype: int64

In [77]:
# titanic datasets

In [78]:
import pandas as pd

df = pd.read_csv("/content/titanic_dataset.csv")
df.head()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S

In [79]:
#Average Fare per Passenger Class
df.groupby('Pclass')['Fare'].mean()

Pclass
1    87.508992
2    21.179196
3    13.302889
Name: Fare, dtype: float64

In [80]:
df.groupby('Sex')['Survived'].mean()
#Survival Rate by Gender

Sex
female    0.82618
male      0.12930
Name: Survived, dtype: float64

In [81]:
# Multiple Aggregations
df.groupby('Pclass')['Fare'].agg(['mean', 'max', 'min', 'count'])

             mean       max  min  count
Pclass
1       87.508992  512.3292  0.0    323
2       21.179196   73.5000  0.0    277
3       13.302889   69.5500  0.0    708

In [82]:
#GroupBy Multiple Columns
df.groupby(['Pclass', 'Sex'])['Survived'].mean()

Pclass  Sex
1       female    0.979167
        male      0.251397
2       female    0.943396
        male      0.099415
3       female    0.666667
        male      0.095335
Name: Survived, dtype: float64

In [83]:
# Average age of survivors vs non-survivors
df.groupby('Survived')['Age'].mean()

Survived
0    30.510986
1    28.931079
Name: Age, dtype: float64

In [84]:
# Count of male and female passengers per class
df.groupby(['Pclass', 'Sex']).size()

Pclass  Sex
1       female    144
        male      179
2       female    106
        male      171
3       female    216
        male      493
dtype: int64

In [85]:
df["average age "]=df.groupby("Sex")["Age"].mean()

In [86]:
df

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked,average age
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S,NaN
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C,NaN
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S,NaN
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S,NaN
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...
1304,1305,0,3,"Spector, Mr. Woolf",male,NaN,0,0,A.5. 3236,8.0500,NaN,S,NaN
1305,1306,1,1,"Oliva y Ocana, Dona. Fermina",female,39.0,0,0,PC 17758,108.9000,C105,C,NaN
1306,1307,0,3,"Saether, Mr. Simon Sivertsen",male,38.5,0,0,SOTON/O.Q. 3101262,7.2500,NaN,S,NaN
1307,1308,0,3,"Ware, Mr. Frederick",male,NaN,0,0,359309,8.0500,NaN,S,NaN
1308,1309,0,3,"Peter, Master. Michael J",male,NaN,1,1,2668,22.3583,NaN,C,NaN

In [87]:
# Which embark town has highest survival rate?

df.groupby("Embarked")["Age"].mean()

Embarked
C    32.332170
Q    28.630000
S    29.245205
Name: Age, dtype: float64

Now your task is to make a 25 question from chatgpt and practcie your self furst write the question and then answer

1. What is groupby() in Pandas?

Answer:
groupby() is used to divide data into groups and perform calculations on each group.

In [95]:
import pandas as pd

data = {
    'Student_ID': [101, 102, 103, 104, 105, 106],
    'Name': ['pratik', 'gaurav', 'Haya', 'Gauri', 'Asha', 'Bikash'],
    'Age': [20, 21, 19, 22, 20, 21],
    'Department': ['IT', 'BCA', 'BIM', 'IT', 'BCA', 'BIM'],
    'Marks': [85, 90, 78, 92, 88, 75],
    'City': ['Kathmandu', 'Pokhara', 'Lalitpur', 'Bhaktapur', 'Chitwan', 'Butwal']
}

df = pd.DataFrame(data)

df

   Student_ID    Name  Age Department  Marks       City
0         101  pratik   20         IT     85  Kathmandu
1         102  gaurav   21        BCA     90    Pokhara
2         103    Haya   19        BIM     78   Lalitpur
3         104   Gauri   22         IT     92  Bhaktapur
4         105    Asha   20        BCA     88    Chitwan
5         106  Bikash   21        BIM     75     Butwal

In [96]:
#1. Display the first 5 rows of the DataFrame.
df.head()

   Student_ID    Name  Age Department  Marks       City
0         101  pratik   20         IT     85  Kathmandu
1         102  gaurav   21        BCA     90    Pokhara
2         103    Haya   19        BIM     78   Lalitpur
3         104   Gauri   22         IT     92  Bhaktapur
4         105    Asha   20        BCA     88    Chitwan

In [97]:
#2. Display all column names.
df.columns

Index(['Student_ID', 'Name', 'Age', 'Department', 'Marks', 'City'], dtype='object')

In [98]:
#3. Find the total number of students.
df['Name'].count()

np.int64(6)

In [99]:
#4. Find the average marks of all students.
df['Marks'].mean()

np.float64(84.66666666666667)

In [100]:
#5. Find the highest marks.
df['Marks'].max()

92

In [101]:
#6. Find the lowest marks.
df['Marks'].min()

75

In [102]:
#7. Group students by Department.
df.groupby('Department')

In [103]:
#8. Find the average marks of each Department.
df.groupby('Department')['Marks'].mean()

Department
BCA    89.0
BIM    76.5
IT     88.5
Name: Marks, dtype: float64

In [104]:
#9. Find the highest marks in each Department.
df.groupby('Department')['Marks'].max()

Department
BCA    90
BIM    78
IT     92
Name: Marks, dtype: int64

In [105]:
#10. Find the lowest marks in each Department.
df.groupby('Department')['Marks'].min()

Department
BCA    88
BIM    75
IT     85
Name: Marks, dtype: int64

In [106]:
#11. Find the total marks of each Department.
df.groupby('Department')['Marks'].sum()

Department
BCA    178
BIM    153
IT     177
Name: Marks, dtype: int64

In [107]:
#12. Count students in each Department.
df.groupby('Department')['Name'].count()

Department
BCA    2
BIM    2
IT     2
Name: Name, dtype: int64

In [108]:
#13. Find the average age of students in each Department.
df.groupby('Department')['Age'].mean()

Department
BCA    20.5
BIM    20.0
IT     21.0
Name: Age, dtype: float64

In [109]:
#14. Find the average marks of students from each City.
df.groupby('City')['Marks'].mean()

City
Bhaktapur    92.0
Butwal       75.0
Chitwan      88.0
Kathmandu    85.0
Lalitpur     78.0
Pokhara      90.0
Name: Marks, dtype: float64

In [110]:
#15. Find the highest marks from each City.
df.groupby('City')['Marks'].max()

City
Bhaktapur    92
Butwal       75
Chitwan      88
Kathmandu    85
Lalitpur     78
Pokhara      90
Name: Marks, dtype: int64

In [111]:
#16. Find the minimum age in each Department.
df.groupby('Department')['Age'].min()

Department
BCA    20
BIM    19
IT     20
Name: Age, dtype: int64

In [112]:
#17. Find the maximum age in each Department.
df.groupby('Department')['Age'].max()

Department
BCA    21
BIM    21
IT     22
Name: Age, dtype: int64

In [113]:
#18. Find average Marks and average Age for each Department.
df.groupby('Department')[['Marks', 'Age']].mean()

            Marks   Age
Department
BCA          89.0  20.5
BIM          76.5  20.0
IT           88.5  21.0

In [114]:
#19. Find maximum Marks and maximum Age for each Department.
df.groupby('Department')[['Marks', 'Age']].max()

            Marks  Age
Department
BCA            90   21
BIM            78   21
IT             92   22

In [115]:
#20. Find minimum Marks and minimum Age for each Department.
df.groupby('Department')[['Marks', 'Age']].min()

            Marks  Age
Department
BCA            88   20
BIM            75   19
IT             85   20

In [116]:
#21. Find multiple calculations for Marks in each Department.
df.groupby('Department')['Marks'].agg(
    ['mean', 'max', 'min', 'sum', 'count']
)

            mean  max  min  sum  count
Department
BCA         89.0   90   88  178      2
BIM         76.5   78   75  153      2
IT          88.5   92   85  177      2

In [117]:
#22. Group students by Department and City.
df.groupby(['Department', 'City'])['Marks'].mean()

Department  City
BCA         Chitwan      88.0
            Pokhara      90.0
BIM         Butwal       75.0
            Lalitpur     78.0
IT          Bhaktapur    92.0
            Kathmandu    85.0
Name: Marks, dtype: float64

In [118]:
#23. Find the average marks according to Department and City.
df.groupby(['Department', 'City'])['Marks'].mean()

Department  City
BCA         Chitwan      88.0
            Pokhara      90.0
BIM         Butwal       75.0
            Lalitpur     78.0
IT          Bhaktapur    92.0
            Kathmandu    85.0
Name: Marks, dtype: float64

In [119]:
#24. Find the total marks according to Department and City.
df.groupby(['Department', 'City'])['Marks'].sum()

Department  City
BCA         Chitwan      88
            Pokhara      90
BIM         Butwal       75
            Lalitpur     78
IT          Bhaktapur    92
            Kathmandu    85
Name: Marks, dtype: int64

In [120]:
#25. Find the highest marks according to Department and City.
df.groupby(['Department', 'City'])['Marks'].max()

Department  City
BCA         Chitwan      88
            Pokhara      90
BIM         Butwal       75
            Lalitpur     78
IT          Bhaktapur    92
            Kathmandu    85
Name: Marks, dtype: int64

In [90]:
import pandas as pd

df1 = pd.DataFrame({
    'id': [1, 2, 3],
    'name': ['A', 'B', 'C']
})
df1

   id name
0   1    A
1   2    B
2   3    C

In [ ]:
df1

In [ ]:
df2 = pd.DataFrame({
    'id': [1, 2, 4],
    'score': [85, 90, 88]
})

In [ ]:
df2

In [ ]:
result = pd.merge(df1, df2, on='id')
print(result)

In [ ]:
pd.merge(df1, df2, on='id', how='inner')
#Keeps common rows only

In [ ]:
# Test with new data
import pandas as pd

students = pd.DataFrame({
    'student_id': [101, 102, 103, 104],
    'student_name': ['Ram', 'Sita', 'Hari', 'Gita'],
    'department': ['CS', 'IT', 'CS', 'BCA']
})

print(students)

In [ ]:
marks = pd.DataFrame({
    'student_id': [101, 102, 105],
    'marks': [88, 92, 75]
})

print(marks)

In [ ]:
inner_join = pd.merge(students, marks, on='student_id', how='inner')
print(inner_join)
# Common records only

In [ ]:
left_join = pd.merge(students, marks, on='student_id', how='left')
print(left_join)

In [ ]:
right_join = pd.merge(students, marks, on='student_id', how='right')
print(right_join)

In [ ]:
outer_join = pd.merge(students, marks, on='student_id', how='outer')
print(outer_join)
# Outer Join (Everything from both tables)

Easy Memory Trick

Inner → common only

Left → everything from first table

Right → everything from second table

Outer → everything from both