### Pandas Series

A Series is a one-dimensional labeled array.

Think of it like:

A single column of a table

Or a vector with labels (index)

In [2]:
import pandas as pd

In [3]:
s = pd.Series([10, 20, 30, 40,50])
s

0    10
1    20
2    30
3    40
4    50
dtype: int64

In [4]:
#series with custom index
marks = pd.Series([85, 90, 88], index=["pratiksha", "gaurav", "hari"])
marks

pratiksha    85
gaurav       90
hari         88
dtype: int64

In [5]:
marks[0]

/tmp/ipykernel_2113/1318454221.py:1: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  marks[0]

np.int64(85)

# Pandas DataFrame (2-D data)
What is a DataFrame?

A DataFrame is a table (rows + columns), like Excel or SQL table

In [6]:
df = pd.DataFrame({
    "Name": ["pratiksha", "gita", "Ram"],
    "Age": [23, 21, 28],
    "Score": [85, 90,85]
})

df

        Name  Age  Score
0  pratiksha   23     85
1       gita   21     90
2        Ram   28     85

### Select Columns (very important)
#### Single column → Series
### Multiple columns → DataFrame

In [7]:
df["Age"]

0    23
1    21
2    28
Name: Age, dtype: int64

In [8]:
df[["Name", "Score"]]

        Name  Score
0  pratiksha     85
1       gita     90
2        Ram     85

In [9]:
### Now use all the general method for this dataframe like and find first 2 data last two data info and shape
df.head()

        Name  Age  Score
0  pratiksha   23     85
1       gita   21     90
2        Ram   28     85

In [10]:
df.tail(5)

        Name  Age  Score
0  pratiksha   23     85
1       gita   21     90
2        Ram   28     85

In [11]:
df.shape

(3, 3)

In [12]:
df.head(1)

        Name  Age  Score
0  pratiksha   23     85

In [13]:
df.sample()

        Name  Age  Score
0  pratiksha   23     85

In [14]:

df = pd.DataFrame({
    "Name": [
        "pratiksha", "gaurav", "anita", "Gita", "Hari", "Nita", "Ravi", "Pooja", "Kiran", "Maya",
        "Amit", "Sneha", "Rohan", "aurav", "Bikash", "Nisha", "Rahul", "Puja", "Suman", "Kavita",
        "Arjun", "Neha", "Sagar", "Rita", "Manish", "Sunita", "Deepak", "Priya", "Rohit", "Alina",
        "Vikas", "Mina", "Nabin", "Komal", "Dipesh", "Laxmi", "Prakash", "Isha", "Niraj", "Asha",
        "Suraj", "Riya", "Santosh", "Anjali", "Hemant", "Pawan", "Monika", "Ashok", "Preeti", "Sonia"
    ],
    "Age": [
        22, 21, 23, 20, 22, 21, 23, 20, 22, 21,
        23, 20, 22, 21, 23, 20, 22, 21, 23, 20,
        22, 21, 23, 20, 22, 21, 23, 20, 22, 21,
        23, 20, 22, 21, 23, 20, 22, 21, 23, 20,
        22, 21, 23, 20, 22, 21, 23, 20, 22, 21
    ],
    "Score": [
        85, 90, 88, 76, 92, 81, 87, 79, 84, 90,
        86, 78, 91, 83, 89, 80, 88, 82, 90, 77,
        85, 84, 92, 79, 88, 81, 90, 83, 87, 86,
        91, 78, 84, 82, 89, 80, 88, 85, 92, 77,
        90, 83, 91, 79, 86, 84, 88, 81, 90, 85
    ]
})

df

         Name  Age  Score
0   pratiksha   22     85
1      gaurav   21     90
2       anita   23     88
3        Gita   20     76
4        Hari   22     92
5        Nita   21     81
6        Ravi   23     87
7       Pooja   20     79
8       Kiran   22     84
9        Maya   21     90
10       Amit   23     86
11      Sneha   20     78
12      Rohan   22     91
13      aurav   21     83
14     Bikash   23     89
15      Nisha   20     80
16      Rahul   22     88
17       Puja   21     82
18      Suman   23     90
19     Kavita   20     77
20      Arjun   22     85
21       Neha   21     84
22      Sagar   23     92
23       Rita   20     79
24     Manish   22     88
25     Sunita   21     81
26     Deepak   23     90
27      Priya   20     83
28      Rohit   22     87
29      Alina   21     86
30      Vikas   23     91
31       Mina   20     78
32      Nabin   22     84
33      Komal   21     82
34     Dipesh   23     89
35      Laxmi   20     80
36    Prakash   22     88
37       Isha   21     85
38      Niraj   23     92
39       Asha   20     77
40      Suraj   22     90
41       Riya   21     83
42    Santosh   23     91
43     Anjali   20     79
44     Hemant   22     86
45      Pawan   21     84
46     Monika   23     88
47      Ashok   20     81
48     Preeti   22     90
49      Sonia   21     85

In [15]:
# save the generated data into local system
df.to_csv('data.csv', index=False)  # index=False avoids adding row numbers

In [16]:
# apply all the analysis like info shape ,describe and others things in your data and find the first 10 and last 10 data
df.head(10)

        Name  Age  Score
0  pratiksha   22     85
1     gaurav   21     90
2      anita   23     88
3       Gita   20     76
4       Hari   22     92
5       Nita   21     81
6       Ravi   23     87
7      Pooja   20     79
8      Kiran   22     84
9       Maya   21     90

In [17]:
df.sample()

    Name  Age  Score
39  Asha   20     77

In [18]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 50 entries, 0 to 49
Data columns (total 3 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   Name    50 non-null     object
 1   Age     50 non-null     int64
 2   Score   50 non-null     int64
dtypes: int64(2), object(1)
memory usage: 1.3+ KB

In [19]:
df.describe()

             Age      Score
count  50.000000  50.000000
mean   21.500000  85.080000
std     1.111168   4.606296
min    20.000000  76.000000
25%    21.000000  81.250000
50%    21.500000  85.000000
75%    22.000000  89.000000
max    23.000000  92.000000

In [20]:
# your task generate the another data using the list

### you can add your own note below using pandas offical documentation https://pandas.pydata.org/docs/

### your task find and write the detailed comparison between series and dataframe with code example

In [21]:
import pandas as pd

# Create a list of student names
students = ["Ram", "Sita", "Hari", "Gita", "Rohan"]

# Create a Series from the list
student_series = pd.Series(students)

print(student_series)

0      Ram
1     Sita
2     Hari
3     Gita
4    Rohan
dtype: object

In [22]:
import pandas as pd

# Create a list of marks
marks = [75, 82, 68, 90, 77]

# Convert list into Series
marks_series = pd.Series(marks)

print(marks_series)

0    75
1    82
2    68
3    90
4    77
dtype: int64

#Pandas
Pandas is a Python library used for working with and analyzing data. It provides two main data structures: Series and DataFrame.

Series → 1-dimensional data
DataFrame → 2-dimensional data with rows and columns

#Detailed Comparison Between Series and DataFrame
In pandas, Series and DataFrame are two important data structures used for storing and analyzing data. A Series is a one-dimensional data structure that contains a single sequence of values along with an index. It is similar to a single column in a table. For example, a Series can be used to store the marks of students. On the other hand, a DataFrame is a two-dimensional data structure that contains rows and columns, similar to a table in Excel. It can store multiple types of information such as student name, age, marks, and address in different columns. A Series has only one dimension, while a DataFrame has two dimensions. A DataFrame can also contain multiple Series, where each column represents a Series. Therefore, Series is mainly used when working with a single column or a single set of data, whereas DataFrame is used when working with a complete dataset containing multiple rows and columns.

#Series Example

In [23]:
import pandas as pd

# Create a Series
marks = pd.Series([75, 82, 68, 90, 77])

print(marks)

0    75
1    82
2    68
3    90
4    77
dtype: int64

In [24]:
print(marks.ndim)

1

#DataFrame Example

In [25]:
import pandas as pd

data = {
    "Name": ["Ram", "Sita", "Hari", "Gita"],
    "Age": [20, 21, 19, 22],
    "Marks": [75, 82, 68, 90]
}

df = pd.DataFrame(data)

print(df)

   Name  Age  Marks
0   Ram   20     75
1  Sita   21     82
2  Hari   19     68
3  Gita   22     90

In [26]:
print(df["Marks"])

0    75
1    82
2    68
3    90
Name: Marks, dtype: int64

#Series vs DataFrame Code Comparison

In [27]:
marks = pd.Series([75, 82, 68, 90])

print(marks)
print(marks.shape)

0    75
1    82
2    68
3    90
dtype: int64
(4,)

#dataframe

In [28]:
data = {
    "Name": ["Ram", "Sita", "Hari", "Gita"],
    "Marks": [75, 82, 68, 90]
}

df = pd.DataFrame(data)

print(df)
print(df.shape)

   Name  Marks
0   Ram     75
1  Sita     82
2  Hari     68
3  Gita     90
(4, 2)

###Series (4,) → 4 values in one dimension
###DataFrame (4, 2) → 4 rows and 2 columns

#indexing compaison

In [29]:
marks = pd.Series([75, 82, 68, 90])

print(marks.iloc[0])

75

###dataframe

In [30]:
print(df.iloc[0])

Name     Ram
Marks     75
Name: 0, dtype: object

In [31]:
print(df["Marks"])

0    75
1    82
2    68
3    90
Name: Marks, dtype: int64