In [1]:
# 1️⃣ Import Pandas Library
# Import pandas to work with DataFrames
import pandas as pd

In [2]:
# 2️⃣ Create a Sample DataFrame
# We will create a DataFrame with columns 'Name', 'Age', 'City'
data = {
    'Name': ['Alice', 'Bob', 'Charlie', 'David'],
    'Age': [25, 30, 35, 40],
    'City': ['Kathmandu', 'Pokhara', 'Lalitpur', 'Biratnagar']
}

df = pd.DataFrame(data)  # Create DataFrame
df

      Name  Age        City
0    Alice   25   Kathmandu
1      Bob   30     Pokhara
2  Charlie   35    Lalitpur
3    David   40  Biratnagar

In [3]:
# 3️⃣ Default Index
# By default, Pandas assigns a numeric index starting from 0
print(df.index)  # Shows the default index

RangeIndex(start=0, stop=4, step=1)

# 4️⃣ Set a Column as Index

In [4]:
df.set_index("Name")

         Age        City
Name
Alice     25   Kathmandu
Bob       30     Pokhara
Charlie   35    Lalitpur
David     40  Biratnagar

permanently set index

In [5]:
df.set_index("Name",inplace=True)

In [6]:
df

         Age        City
Name
Alice     25   Kathmandu
Bob       30     Pokhara
Charlie   35    Lalitpur
David     40  Biratnagar

In [7]:
# 6️⃣ Reset Index

df.reset_index()

      Name  Age        City
0    Alice   25   Kathmandu
1      Bob   30     Pokhara
2  Charlie   35    Lalitpur
3    David   40  Biratnagar

In [8]:
# 6️⃣ Reset Index

df.reset_index(inplace=True)

### What does inplace=True mean?

- `inplace=True` means **modify the original DataFrame**
- No new DataFrame is created
- Changes happen **permanently**

### Example:
Without inplace:
```python
new_df = df.set_index("Student_ID")

In [9]:
import pandas as pd
# Creating a simple DataFrame
data = {
    "Student_ID": [101, 102, 103, 104],
    "Name": ["Ram", "Sita", "Hari", "Gita"],
    "Marks": [85, 90, 78, 92]
}

df = pd.DataFrame(data)

# Display the DataFrame
df

   Student_ID  Name  Marks
0         101   Ram     85
1         102  Sita     90
2         103  Hari     78
3         104  Gita     92

In [10]:
df.set_index("Student_ID")

            Name  Marks
Student_ID
101          Ram     85
102         Sita     90
103         Hari     78
104         Gita     92

In [11]:
df.set_index("Student_ID", inplace=True)

In [12]:
df

            Name  Marks
Student_ID
101          Ram     85
102         Sita     90
103         Hari     78
104         Gita     92

task create a one data and practcie all like make index reset test with inplace

# Pandas Index Practice Task

Practice **default index, set index, reset index, and inplace=True** using one dataset.

## Dataset
Student information with Student_ID, Name, Age, Department, Marks, and City.

In [13]:
# 1. Import pandas
import pandas as pd

In [14]:
# 2. Create the dataset
data = {
    'Student_ID': [101, 102, 103, 104, 105, 106],
    'Name': ['Ram', 'Sita', 'Hari', 'Gita', 'Asha', 'Bikash'],
    'Age': [20, 21, 19, 22, 20, 21],
    'Department': ['IT', 'BCA', 'BIM', 'IT', 'BCA', 'BIM'],
    'Marks': [85, 90, 78, 92, 88, 75],
    'City': ['Kathmandu', 'Pokhara', 'Lalitpur', 'Bhaktapur', 'Chitwan', 'Butwal']
}

df = pd.DataFrame(data)
df

   Student_ID    Name  Age Department  Marks       City
0         101     Ram   20         IT     85  Kathmandu
1         102    Sita   21        BCA     90    Pokhara
2         103    Hari   19        BIM     78   Lalitpur
3         104    Gita   22         IT     92  Bhaktapur
4         105    Asha   20        BCA     88    Chitwan
5         106  Bikash   21        BIM     75     Butwal

## Task 1: Check the Default Index

In [15]:
# Write code to display the index of df
df.index

RangeIndex(start=0, stop=6, step=1)

## Task 2: Set Student_ID as the Index (without inplace)

**Goal:** Create a new DataFrame named df_indexed.

In [16]:
df_indexed = df.set_index('Student_ID')
df_indexed

              Name  Age Department  Marks       City
Student_ID
101            Ram   20         IT     85  Kathmandu
102           Sita   21        BCA     90    Pokhara
103           Hari   19        BIM     78   Lalitpur
104           Gita   22         IT     92  Bhaktapur
105           Asha   20        BCA     88    Chitwan
106         Bikash   21        BIM     75     Butwal

## Task 3: Test whether the original df changed

If inplace=False (default), the original DataFrame should still have the normal numeric index.

In [17]:
# Check the original df
df

   Student_ID    Name  Age Department  Marks       City
0         101     Ram   20         IT     85  Kathmandu
1         102    Sita   21        BCA     90    Pokhara
2         103    Hari   19        BIM     78   Lalitpur
3         104    Gita   22         IT     92  Bhaktapur
4         105    Asha   20        BCA     88    Chitwan
5         106  Bikash   21        BIM     75     Butwal

## Task 4: Set Student_ID as the Index with inplace=True

Now change the **original** df.

In [18]:
df.set_index('Student_ID', inplace=True)
df

              Name  Age Department  Marks       City
Student_ID
101            Ram   20         IT     85  Kathmandu
102           Sita   21        BCA     90    Pokhara
103           Hari   19        BIM     78   Lalitpur
104           Gita   22         IT     92  Bhaktapur
105           Asha   20        BCA     88    Chitwan
106         Bikash   21        BIM     75     Butwal

## Task 5: Test inplace=True

Check whether Student_ID is now the index of the original df.

In [19]:
df.index

Index([101, 102, 103, 104, 105, 106], dtype='int64', name='Student_ID')

## Task 6: Reset the Index (without inplace)

Create a new DataFrame named df_reset.

In [20]:
df_reset = df.reset_index()
df_reset

   Student_ID    Name  Age Department  Marks       City
0         101     Ram   20         IT     85  Kathmandu
1         102    Sita   21        BCA     90    Pokhara
2         103    Hari   19        BIM     78   Lalitpur
3         104    Gita   22         IT     92  Bhaktapur
4         105    Asha   20        BCA     88    Chitwan
5         106  Bikash   21        BIM     75     Butwal

## Task 7: Test the original df again

Because inplace was not used in Task 6, the original df should still have Student_ID as its index.

In [21]:
df

              Name  Age Department  Marks       City
Student_ID
101            Ram   20         IT     85  Kathmandu
102           Sita   21        BCA     90    Pokhara
103           Hari   19        BIM     78   Lalitpur
104           Gita   22         IT     92  Bhaktapur
105           Asha   20        BCA     88    Chitwan
106         Bikash   21        BIM     75     Butwal

## Task 8: Reset the Index with inplace=True

Now permanently reset the index of the original df.

In [22]:
df.reset_index(inplace=True)
df

   Student_ID    Name  Age Department  Marks       City
0         101     Ram   20         IT     85  Kathmandu
1         102    Sita   21        BCA     90    Pokhara
2         103    Hari   19        BIM     78   Lalitpur
3         104    Gita   22         IT     92  Bhaktapur
4         105    Asha   20        BCA     88    Chitwan
5         106  Bikash   21        BIM     75     Butwal