In [6]:
import pandas as pd

# Load Dataset
df = pd.read_csv("/content/sales_practice_dataset.csv")

# Display dataset
df

,Order_ID,Customer,Product,Category,City,Quantity,Price,Rating
0,1001,Aarav,Laptop,Electronics,Kathmandu,2,80000,4.5
1,1002,Sita,Phone,Electronics,Pokhara,3,50000,4.2
2,1003,Rohan,Headphone,Accessories,Lalitpur,5,3000,4.0
3,1004,Maya,Laptop,Electronics,Kathmandu,1,85000,4.8
4,1005,Bibek,Tablet,Electronics,Bhaktapur,2,35000,3.9
5,1006,Anu,Phone,Electronics,Pokhara,4,48000,4.4
6,1007,Suman,Mouse,Accessories,Kathmandu,6,1200,4.1
7,1008,Priya,Keyboard,Accessories,Lalitpur,3,2500,4.3
8,1009,Nabin,Phone,Electronics,Bhaktapur,2,52000,4.6
9,1010,Kiran,Laptop,Electronics,Pokhara,1,90000,4.7
10,1011,Riya,Tablet,Electronics,Kathmandu,3,38000,4.0
11,1012,Aashish,Headphone,Accessories,Lalitpur,4,3500,3.8
12,1013,Puja,Mouse,Accessories,Bhaktapur,5,1000,4.2
13,1014,Roshan,Phone,Electronics,Kathmandu,2,51000,4.5
14,1015,Sneha,Keyboard,Accessories,Pokhara,6,2800,4.1
15,1016,Dipak,Laptop,Electronics,Lalitpur,1,82000,4.9
16,1017,Sabina,Tablet,Electronics,Kathmandu,3,36000,3.7
17,1018,Raj,Mouse,Accessories,Bhaktapur,7,1100,4.4
18,1019,Nisha,Phone,Electronics,Pokhara,2,49000,4.3
19,1020,Manish,Headphone,Accessories,Kathmandu,4,3200,3.9

In [7]:
# 1. Display the first 5 rows
df.head()

,Order_ID,Customer,Product,Category,City,Quantity,Price,Rating
0,1001,Aarav,Laptop,Electronics,Kathmandu,2,80000,4.5
1,1002,Sita,Phone,Electronics,Pokhara,3,50000,4.2
2,1003,Rohan,Headphone,Accessories,Lalitpur,5,3000,4.0
3,1004,Maya,Laptop,Electronics,Kathmandu,1,85000,4.8
4,1005,Bibek,Tablet,Electronics,Bhaktapur,2,35000,3.9

In [8]:
# 2. Display the last 5 rows
df.tail()

,Order_ID,Customer,Product,Category,City,Quantity,Price,Rating
15,1016,Dipak,Laptop,Electronics,Lalitpur,1,82000,4.9
16,1017,Sabina,Tablet,Electronics,Kathmandu,3,36000,3.7
17,1018,Raj,Mouse,Accessories,Bhaktapur,7,1100,4.4
18,1019,Nisha,Phone,Electronics,Pokhara,2,49000,4.3
19,1020,Manish,Headphone,Accessories,Kathmandu,4,3200,3.9

In [9]:
# 3. Display all column names
df.columns

Index(['Order_ID', 'Customer', 'Product', 'Category', 'City', 'Quantity',
       'Price', 'Rating'],
      dtype='object')

In [10]:
# 4. Display the shape of the dataset
df.shape

(20, 8)

In [11]:
# 5. Select only the Customer column
df["Customer"]

0       Aarav
1        Sita
2       Rohan
3        Maya
4       Bibek
5         Anu
6       Suman
7       Priya
8       Nabin
9       Kiran
10       Riya
11    Aashish
12       Puja
13     Roshan
14      Sneha
15      Dipak
16     Sabina
17        Raj
18      Nisha
19     Manish
Name: Customer, dtype: object

In [13]:
# 6. Select Product and Price columns
df[["Product", "Price"]]

      Product  Price
0      Laptop  80000
1       Phone  50000
2   Headphone   3000
3      Laptop  85000
4      Tablet  35000
5       Phone  48000
6       Mouse   1200
7    Keyboard   2500
8       Phone  52000
9      Laptop  90000
10     Tablet  38000
11  Headphone   3500
12      Mouse   1000
13      Phone  51000
14   Keyboard   2800
15     Laptop  82000
16     Tablet  36000
17      Mouse   1100
18      Phone  49000
19  Headphone   3200

In [14]:
# 7. Display all customers from Kathmandu
df.loc[df["City"] == "Kathmandu"]

,Order_ID,Customer,Product,Category,City,Quantity,Price,Rating
0,1001,Aarav,Laptop,Electronics,Kathmandu,2,80000,4.5
3,1004,Maya,Laptop,Electronics,Kathmandu,1,85000,4.8
6,1007,Suman,Mouse,Accessories,Kathmandu,6,1200,4.1
10,1011,Riya,Tablet,Electronics,Kathmandu,3,38000,4.0
13,1014,Roshan,Phone,Electronics,Kathmandu,2,51000,4.5
16,1017,Sabina,Tablet,Electronics,Kathmandu,3,36000,3.7
19,1020,Manish,Headphone,Accessories,Kathmandu,4,3200,3.9

In [15]:
# 8. Display all customers from Pokhara
df.loc[df["City"] == "Pokhara"]

    Order_ID Customer   Product     Category     City  Quantity  Price  Rating
1       1002     Sita     Phone  Electronics  Pokhara         3  50000     4.2
5       1006      Anu     Phone  Electronics  Pokhara         4  48000     4.4
9       1010    Kiran    Laptop  Electronics  Pokhara         1  90000     4.7
14      1015    Sneha  Keyboard  Accessories  Pokhara         6   2800     4.1
18      1019    Nisha     Phone  Electronics  Pokhara         2  49000     4.3

In [16]:
# 9. Display all customers who bought Laptop
df.loc[df["Product"] == "Laptop"]

    Order_ID Customer Product     Category       City  Quantity  Price  Rating
0       1001    Aarav  Laptop  Electronics  Kathmandu         2  80000     4.5
3       1004     Maya  Laptop  Electronics  Kathmandu         1  85000     4.8
9       1010    Kiran  Laptop  Electronics    Pokhara         1  90000     4.7
15      1016    Dipak  Laptop  Electronics   Lalitpur         1  82000     4.9

In [17]:
# 10. Display all orders where Product is Phone
df.loc[df["Product"] == "Phone"]

    Order_ID Customer Product     Category       City  Quantity  Price  Rating
1       1002     Sita   Phone  Electronics    Pokhara         3  50000     4.2
5       1006      Anu   Phone  Electronics    Pokhara         4  48000     4.4
8       1009    Nabin   Phone  Electronics  Bhaktapur         2  52000     4.6
13      1014   Roshan   Phone  Electronics  Kathmandu         2  51000     4.5
18      1019    Nisha   Phone  Electronics    Pokhara         2  49000     4.3

In [18]:
# 11. Price greater than 50000
df.loc[df["Price"] > 50000]

    Order_ID Customer Product     Category       City  Quantity  Price  Rating
0       1001    Aarav  Laptop  Electronics  Kathmandu         2  80000     4.5
3       1004     Maya  Laptop  Electronics  Kathmandu         1  85000     4.8
8       1009    Nabin   Phone  Electronics  Bhaktapur         2  52000     4.6
9       1010    Kiran  Laptop  Electronics    Pokhara         1  90000     4.7
13      1014   Roshan   Phone  Electronics  Kathmandu         2  51000     4.5
15      1016    Dipak  Laptop  Electronics   Lalitpur         1  82000     4.9

In [19]:
# 12. Price less than 50000
df.loc[df["Price"] < 50000]

,Order_ID,Customer,Product,Category,City,Quantity,Price,Rating
2,1003,Rohan,Headphone,Accessories,Lalitpur,5,3000,4.0
4,1005,Bibek,Tablet,Electronics,Bhaktapur,2,35000,3.9
5,1006,Anu,Phone,Electronics,Pokhara,4,48000,4.4
6,1007,Suman,Mouse,Accessories,Kathmandu,6,1200,4.1
7,1008,Priya,Keyboard,Accessories,Lalitpur,3,2500,4.3
10,1011,Riya,Tablet,Electronics,Kathmandu,3,38000,4.0
11,1012,Aashish,Headphone,Accessories,Lalitpur,4,3500,3.8
12,1013,Puja,Mouse,Accessories,Bhaktapur,5,1000,4.2
14,1015,Sneha,Keyboard,Accessories,Pokhara,6,2800,4.1
16,1017,Sabina,Tablet,Electronics,Kathmandu,3,36000,3.7
17,1018,Raj,Mouse,Accessories,Bhaktapur,7,1100,4.4
18,1019,Nisha,Phone,Electronics,Pokhara,2,49000,4.3
19,1020,Manish,Headphone,Accessories,Kathmandu,4,3200,3.9

In [20]:
# 13. Quantity greater than 3
df.loc[df["Quantity"] > 3]

,Order_ID,Customer,Product,Category,City,Quantity,Price,Rating
2,1003,Rohan,Headphone,Accessories,Lalitpur,5,3000,4.0
5,1006,Anu,Phone,Electronics,Pokhara,4,48000,4.4
6,1007,Suman,Mouse,Accessories,Kathmandu,6,1200,4.1
11,1012,Aashish,Headphone,Accessories,Lalitpur,4,3500,3.8
12,1013,Puja,Mouse,Accessories,Bhaktapur,5,1000,4.2
14,1015,Sneha,Keyboard,Accessories,Pokhara,6,2800,4.1
17,1018,Raj,Mouse,Accessories,Bhaktapur,7,1100,4.4
19,1020,Manish,Headphone,Accessories,Kathmandu,4,3200,3.9

In [21]:
# 14. Quantity equal to 2
df.loc[df["Quantity"] == 2]

    Order_ID Customer Product     Category       City  Quantity  Price  Rating
0       1001    Aarav  Laptop  Electronics  Kathmandu         2  80000     4.5
4       1005    Bibek  Tablet  Electronics  Bhaktapur         2  35000     3.9
8       1009    Nabin   Phone  Electronics  Bhaktapur         2  52000     4.6
13      1014   Roshan   Phone  Electronics  Kathmandu         2  51000     4.5
18      1019    Nisha   Phone  Electronics    Pokhara         2  49000     4.3

In [22]:
# 15. Rating greater than 4.5
df.loc[df["Rating"] > 4.5]

    Order_ID Customer Product     Category       City  Quantity  Price  Rating
3       1004     Maya  Laptop  Electronics  Kathmandu         1  85000     4.8
8       1009    Nabin   Phone  Electronics  Bhaktapur         2  52000     4.6
9       1010    Kiran  Laptop  Electronics    Pokhara         1  90000     4.7
15      1016    Dipak  Laptop  Electronics   Lalitpur         1  82000     4.9

In [23]:
# 16. Rating less than 4.0
df.loc[df["Rating"] < 4.0]

,Order_ID,Customer,Product,Category,City,Quantity,Price,Rating
4,1005,Bibek,Tablet,Electronics,Bhaktapur,2,35000,3.9
11,1012,Aashish,Headphone,Accessories,Lalitpur,4,3500,3.8
16,1017,Sabina,Tablet,Electronics,Kathmandu,3,36000,3.7
19,1020,Manish,Headphone,Accessories,Kathmandu,4,3200,3.9

In [24]:
# 17. Category is Electronics
df.loc[df["Category"] == "Electronics"]

    Order_ID Customer Product     Category       City  Quantity  Price  Rating
0       1001    Aarav  Laptop  Electronics  Kathmandu         2  80000     4.5
1       1002     Sita   Phone  Electronics    Pokhara         3  50000     4.2
3       1004     Maya  Laptop  Electronics  Kathmandu         1  85000     4.8
4       1005    Bibek  Tablet  Electronics  Bhaktapur         2  35000     3.9
5       1006      Anu   Phone  Electronics    Pokhara         4  48000     4.4
8       1009    Nabin   Phone  Electronics  Bhaktapur         2  52000     4.6
9       1010    Kiran  Laptop  Electronics    Pokhara         1  90000     4.7
10      1011     Riya  Tablet  Electronics  Kathmandu         3  38000     4.0
13      1014   Roshan   Phone  Electronics  Kathmandu         2  51000     4.5
15      1016    Dipak  Laptop  Electronics   Lalitpur         1  82000     4.9
16      1017   Sabina  Tablet  Electronics  Kathmandu         3  36000     3.7
18      1019    Nisha   Phone  Electronics    Pokhara         2  49000     4.3

In [25]:
# 18. Category is Accessories
df.loc[df["Category"] == "Accessories"]

,Order_ID,Customer,Product,Category,City,Quantity,Price,Rating
2,1003,Rohan,Headphone,Accessories,Lalitpur,5,3000,4.0
6,1007,Suman,Mouse,Accessories,Kathmandu,6,1200,4.1
7,1008,Priya,Keyboard,Accessories,Lalitpur,3,2500,4.3
11,1012,Aashish,Headphone,Accessories,Lalitpur,4,3500,3.8
12,1013,Puja,Mouse,Accessories,Bhaktapur,5,1000,4.2
14,1015,Sneha,Keyboard,Accessories,Pokhara,6,2800,4.1
17,1018,Raj,Mouse,Accessories,Bhaktapur,7,1100,4.4
19,1020,Manish,Headphone,Accessories,Kathmandu,4,3200,3.9

In [26]:
# 19. City is Lalitpur
df.loc[df["City"] == "Lalitpur"]

,Order_ID,Customer,Product,Category,City,Quantity,Price,Rating
2,1003,Rohan,Headphone,Accessories,Lalitpur,5,3000,4.0
7,1008,Priya,Keyboard,Accessories,Lalitpur,3,2500,4.3
11,1012,Aashish,Headphone,Accessories,Lalitpur,4,3500,3.8
15,1016,Dipak,Laptop,Electronics,Lalitpur,1,82000,4.9

In [27]:
# 20. City is Bhaktapur
df.loc[df["City"] == "Bhaktapur"]

    Order_ID Customer Product     Category       City  Quantity  Price  Rating
4       1005    Bibek  Tablet  Electronics  Bhaktapur         2  35000     3.9
8       1009    Nabin   Phone  Electronics  Bhaktapur         2  52000     4.6
12      1013     Puja   Mouse  Accessories  Bhaktapur         5   1000     4.2
17      1018      Raj   Mouse  Accessories  Bhaktapur         7   1100     4.4

In [28]:
# 21. Laptop orders from Kathmandu
df.loc[
    (df["Product"] == "Laptop") &
    (df["City"] == "Kathmandu")
]

   Order_ID Customer Product     Category       City  Quantity  Price  Rating
0      1001    Aarav  Laptop  Electronics  Kathmandu         2  80000     4.5
3      1004     Maya  Laptop  Electronics  Kathmandu         1  85000     4.8

In [29]:
# 22. Phone orders from Pokhara
df.loc[
    (df["Product"] == "Phone") &
    (df["City"] == "Pokhara")
]

    Order_ID Customer Product     Category     City  Quantity  Price  Rating
1       1002     Sita   Phone  Electronics  Pokhara         3  50000     4.2
5       1006      Anu   Phone  Electronics  Pokhara         4  48000     4.4
18      1019    Nisha   Phone  Electronics  Pokhara         2  49000     4.3

In [30]:
# 23. Price > 50000 AND Rating > 4.5
df.loc[
    (df["Price"] > 50000) &
    (df["Rating"] > 4.5)
]

    Order_ID Customer Product     Category       City  Quantity  Price  Rating
3       1004     Maya  Laptop  Electronics  Kathmandu         1  85000     4.8
8       1009    Nabin   Phone  Electronics  Bhaktapur         2  52000     4.6
9       1010    Kiran  Laptop  Electronics    Pokhara         1  90000     4.7
15      1016    Dipak  Laptop  Electronics   Lalitpur         1  82000     4.9

In [31]:
# 24. Quantity > 3 AND Price > 30000
df.loc[
    (df["Quantity"] > 3) &
    (df["Price"] > 30000)
]

   Order_ID Customer Product     Category     City  Quantity  Price  Rating
5      1006      Anu   Phone  Electronics  Pokhara         4  48000     4.4

In [32]:
# 25. Electronics AND Kathmandu
df.loc[
    (df["Category"] == "Electronics") &
    (df["City"] == "Kathmandu")
]

    Order_ID Customer Product     Category       City  Quantity  Price  Rating
0       1001    Aarav  Laptop  Electronics  Kathmandu         2  80000     4.5
3       1004     Maya  Laptop  Electronics  Kathmandu         1  85000     4.8
10      1011     Riya  Tablet  Electronics  Kathmandu         3  38000     4.0
13      1014   Roshan   Phone  Electronics  Kathmandu         2  51000     4.5
16      1017   Sabina  Tablet  Electronics  Kathmandu         3  36000     3.7

In [33]:
# 26. Accessories AND Rating > 4.0
df.loc[
    (df["Category"] == "Accessories") &
    (df["Rating"] > 4.0)
]

,Order_ID,Customer,Product,Category,City,Quantity,Price,Rating
6,1007,Suman,Mouse,Accessories,Kathmandu,6,1200,4.1
7,1008,Priya,Keyboard,Accessories,Lalitpur,3,2500,4.3
12,1013,Puja,Mouse,Accessories,Bhaktapur,5,1000,4.2
14,1015,Sneha,Keyboard,Accessories,Pokhara,6,2800,4.1
17,1018,Raj,Mouse,Accessories,Bhaktapur,7,1100,4.4

In [34]:
# 27. Laptop AND Quantity > 2
df.loc[
    (df["Product"] == "Laptop") &
    (df["Quantity"] > 2)
]

Empty DataFrame
Columns: [Order_ID, Customer, Product, Category, City, Quantity, Price, Rating]
Index: []

In [35]:
# 28. Phone AND Price > 50000
df.loc[
    (df["Product"] == "Phone") &
    (df["Price"] > 50000)
]

    Order_ID Customer Product     Category       City  Quantity  Price  Rating
8       1009    Nabin   Phone  Electronics  Bhaktapur         2  52000     4.6
13      1014   Roshan   Phone  Electronics  Kathmandu         2  51000     4.5

In [36]:
# 29. Rating > 4.0 AND Quantity > 3
df.loc[
    (df["Rating"] > 4.0) &
    (df["Quantity"] > 3)
]

,Order_ID,Customer,Product,Category,City,Quantity,Price,Rating
5,1006,Anu,Phone,Electronics,Pokhara,4,48000,4.4
6,1007,Suman,Mouse,Accessories,Kathmandu,6,1200,4.1
12,1013,Puja,Mouse,Accessories,Bhaktapur,5,1000,4.2
14,1015,Sneha,Keyboard,Accessories,Pokhara,6,2800,4.1
17,1018,Raj,Mouse,Accessories,Bhaktapur,7,1100,4.4

In [37]:
# 30. Kathmandu AND Price > 50000
df.loc[
    (df["City"] == "Kathmandu") &
    (df["Price"] > 50000)
]

    Order_ID Customer Product     Category       City  Quantity  Price  Rating
0       1001    Aarav  Laptop  Electronics  Kathmandu         2  80000     4.5
3       1004     Maya  Laptop  Electronics  Kathmandu         1  85000     4.8
13      1014   Roshan   Phone  Electronics  Kathmandu         2  51000     4.5

In [38]:
# 31. Kathmandu OR Pokhara
df.loc[
    (df["City"] == "Kathmandu") |
    (df["City"] == "Pokhara")
]

,Order_ID,Customer,Product,Category,City,Quantity,Price,Rating
0,1001,Aarav,Laptop,Electronics,Kathmandu,2,80000,4.5
1,1002,Sita,Phone,Electronics,Pokhara,3,50000,4.2
3,1004,Maya,Laptop,Electronics,Kathmandu,1,85000,4.8
5,1006,Anu,Phone,Electronics,Pokhara,4,48000,4.4
6,1007,Suman,Mouse,Accessories,Kathmandu,6,1200,4.1
9,1010,Kiran,Laptop,Electronics,Pokhara,1,90000,4.7
10,1011,Riya,Tablet,Electronics,Kathmandu,3,38000,4.0
13,1014,Roshan,Phone,Electronics,Kathmandu,2,51000,4.5
14,1015,Sneha,Keyboard,Accessories,Pokhara,6,2800,4.1
16,1017,Sabina,Tablet,Electronics,Kathmandu,3,36000,3.7
18,1019,Nisha,Phone,Electronics,Pokhara,2,49000,4.3
19,1020,Manish,Headphone,Accessories,Kathmandu,4,3200,3.9

In [39]:
# 32. Laptop OR Phone
df.loc[
    (df["Product"] == "Laptop") |
    (df["Product"] == "Phone")
]

    Order_ID Customer Product     Category       City  Quantity  Price  Rating
0       1001    Aarav  Laptop  Electronics  Kathmandu         2  80000     4.5
1       1002     Sita   Phone  Electronics    Pokhara         3  50000     4.2
3       1004     Maya  Laptop  Electronics  Kathmandu         1  85000     4.8
5       1006      Anu   Phone  Electronics    Pokhara         4  48000     4.4
8       1009    Nabin   Phone  Electronics  Bhaktapur         2  52000     4.6
9       1010    Kiran  Laptop  Electronics    Pokhara         1  90000     4.7
13      1014   Roshan   Phone  Electronics  Kathmandu         2  51000     4.5
15      1016    Dipak  Laptop  Electronics   Lalitpur         1  82000     4.9
18      1019    Nisha   Phone  Electronics    Pokhara         2  49000     4.3

In [40]:
# 33. Price > 80000 OR Price < 3000
df.loc[
    (df["Price"] > 80000) |
    (df["Price"] < 3000)
]

,Order_ID,Customer,Product,Category,City,Quantity,Price,Rating
3,1004,Maya,Laptop,Electronics,Kathmandu,1,85000,4.8
6,1007,Suman,Mouse,Accessories,Kathmandu,6,1200,4.1
7,1008,Priya,Keyboard,Accessories,Lalitpur,3,2500,4.3
9,1010,Kiran,Laptop,Electronics,Pokhara,1,90000,4.7
12,1013,Puja,Mouse,Accessories,Bhaktapur,5,1000,4.2
14,1015,Sneha,Keyboard,Accessories,Pokhara,6,2800,4.1
15,1016,Dipak,Laptop,Electronics,Lalitpur,1,82000,4.9
17,1018,Raj,Mouse,Accessories,Bhaktapur,7,1100,4.4

In [41]:
# 34. Quantity is 5 OR 6
df.loc[
    (df["Quantity"] == 5) |
    (df["Quantity"] == 6)
]

,Order_ID,Customer,Product,Category,City,Quantity,Price,Rating
2,1003,Rohan,Headphone,Accessories,Lalitpur,5,3000,4.0
6,1007,Suman,Mouse,Accessories,Kathmandu,6,1200,4.1
12,1013,Puja,Mouse,Accessories,Bhaktapur,5,1000,4.2
14,1015,Sneha,Keyboard,Accessories,Pokhara,6,2800,4.1

In [42]:
# 35. Rating > 4.5 OR Rating < 3.8
df.loc[
    (df["Rating"] > 4.5) |
    (df["Rating"] < 3.8)
]

    Order_ID Customer Product     Category       City  Quantity  Price  Rating
3       1004     Maya  Laptop  Electronics  Kathmandu         1  85000     4.8
8       1009    Nabin   Phone  Electronics  Bhaktapur         2  52000     4.6
9       1010    Kiran  Laptop  Electronics    Pokhara         1  90000     4.7
15      1016    Dipak  Laptop  Electronics   Lalitpur         1  82000     4.9
16      1017   Sabina  Tablet  Electronics  Kathmandu         3  36000     3.7

In [43]:
# 36. Kathmandu OR Lalitpur
df.loc[
    (df["City"] == "Kathmandu") |
    (df["City"] == "Lalitpur")
]

,Order_ID,Customer,Product,Category,City,Quantity,Price,Rating
0,1001,Aarav,Laptop,Electronics,Kathmandu,2,80000,4.5
2,1003,Rohan,Headphone,Accessories,Lalitpur,5,3000,4.0
3,1004,Maya,Laptop,Electronics,Kathmandu,1,85000,4.8
6,1007,Suman,Mouse,Accessories,Kathmandu,6,1200,4.1
7,1008,Priya,Keyboard,Accessories,Lalitpur,3,2500,4.3
10,1011,Riya,Tablet,Electronics,Kathmandu,3,38000,4.0
11,1012,Aashish,Headphone,Accessories,Lalitpur,4,3500,3.8
13,1014,Roshan,Phone,Electronics,Kathmandu,2,51000,4.5
15,1016,Dipak,Laptop,Electronics,Lalitpur,1,82000,4.9
16,1017,Sabina,Tablet,Electronics,Kathmandu,3,36000,3.7
19,1020,Manish,Headphone,Accessories,Kathmandu,4,3200,3.9

In [44]:
# 37. Electronics OR Accessories
df.loc[
    (df["Category"] == "Electronics") |
    (df["Category"] == "Accessories")
]

,Order_ID,Customer,Product,Category,City,Quantity,Price,Rating
0,1001,Aarav,Laptop,Electronics,Kathmandu,2,80000,4.5
1,1002,Sita,Phone,Electronics,Pokhara,3,50000,4.2
2,1003,Rohan,Headphone,Accessories,Lalitpur,5,3000,4.0
3,1004,Maya,Laptop,Electronics,Kathmandu,1,85000,4.8
4,1005,Bibek,Tablet,Electronics,Bhaktapur,2,35000,3.9
5,1006,Anu,Phone,Electronics,Pokhara,4,48000,4.4
6,1007,Suman,Mouse,Accessories,Kathmandu,6,1200,4.1
7,1008,Priya,Keyboard,Accessories,Lalitpur,3,2500,4.3
8,1009,Nabin,Phone,Electronics,Bhaktapur,2,52000,4.6
9,1010,Kiran,Laptop,Electronics,Pokhara,1,90000,4.7
10,1011,Riya,Tablet,Electronics,Kathmandu,3,38000,4.0
11,1012,Aashish,Headphone,Accessories,Lalitpur,4,3500,3.8
12,1013,Puja,Mouse,Accessories,Bhaktapur,5,1000,4.2
13,1014,Roshan,Phone,Electronics,Kathmandu,2,51000,4.5
14,1015,Sneha,Keyboard,Accessories,Pokhara,6,2800,4.1
15,1016,Dipak,Laptop,Electronics,Lalitpur,1,82000,4.9
16,1017,Sabina,Tablet,Electronics,Kathmandu,3,36000,3.7
17,1018,Raj,Mouse,Accessories,Bhaktapur,7,1100,4.4
18,1019,Nisha,Phone,Electronics,Pokhara,2,49000,4.3
19,1020,Manish,Headphone,Accessories,Kathmandu,4,3200,3.9

In [45]:
# 38. Tablet OR Headphone
df.loc[
    (df["Product"] == "Tablet") |
    (df["Product"] == "Headphone")
]

,Order_ID,Customer,Product,Category,City,Quantity,Price,Rating
2,1003,Rohan,Headphone,Accessories,Lalitpur,5,3000,4.0
4,1005,Bibek,Tablet,Electronics,Bhaktapur,2,35000,3.9
10,1011,Riya,Tablet,Electronics,Kathmandu,3,38000,4.0
11,1012,Aashish,Headphone,Accessories,Lalitpur,4,3500,3.8
16,1017,Sabina,Tablet,Electronics,Kathmandu,3,36000,3.7
19,1020,Manish,Headphone,Accessories,Kathmandu,4,3200,3.9

In [46]:
# 39. Price > 50000 OR Quantity > 5
df.loc[
    (df["Price"] > 50000) |
    (df["Quantity"] > 5)
]

,Order_ID,Customer,Product,Category,City,Quantity,Price,Rating
0,1001,Aarav,Laptop,Electronics,Kathmandu,2,80000,4.5
3,1004,Maya,Laptop,Electronics,Kathmandu,1,85000,4.8
6,1007,Suman,Mouse,Accessories,Kathmandu,6,1200,4.1
8,1009,Nabin,Phone,Electronics,Bhaktapur,2,52000,4.6
9,1010,Kiran,Laptop,Electronics,Pokhara,1,90000,4.7
13,1014,Roshan,Phone,Electronics,Kathmandu,2,51000,4.5
14,1015,Sneha,Keyboard,Accessories,Pokhara,6,2800,4.1
15,1016,Dipak,Laptop,Electronics,Lalitpur,1,82000,4.9
17,1018,Raj,Mouse,Accessories,Bhaktapur,7,1100,4.4

In [47]:
# 40. Rating < 4.0 OR Rating > 4.7
df.loc[
    (df["Rating"] < 4.0) |
    (df["Rating"] > 4.7)
]

,Order_ID,Customer,Product,Category,City,Quantity,Price,Rating
3,1004,Maya,Laptop,Electronics,Kathmandu,1,85000,4.8
4,1005,Bibek,Tablet,Electronics,Bhaktapur,2,35000,3.9
11,1012,Aashish,Headphone,Accessories,Lalitpur,4,3500,3.8
15,1016,Dipak,Laptop,Electronics,Lalitpur,1,82000,4.9
16,1017,Sabina,Tablet,Electronics,Kathmandu,3,36000,3.7
19,1020,Manish,Headphone,Accessories,Kathmandu,4,3200,3.9

In [48]:
# 41. Customer and Product from Kathmandu
df.loc[
    df["City"] == "Kathmandu",
    ["Customer", "Product"]
]

   Customer    Product
0     Aarav     Laptop
3      Maya     Laptop
6     Suman      Mouse
10     Riya     Tablet
13   Roshan      Phone
16   Sabina     Tablet
19   Manish  Headphone

In [49]:
# 42. Customer and Price where Price > 50000
df.loc[
    df["Price"] > 50000,
    ["Customer", "Price"]
]

   Customer  Price
0     Aarav  80000
3      Maya  85000
8     Nabin  52000
9     Kiran  90000
13   Roshan  51000
15    Dipak  82000

In [50]:
# 43. Customer, City and Price for Laptop orders
df.loc[
    df["Product"] == "Laptop",
    ["Customer", "City", "Price"]
]

   Customer       City  Price
0     Aarav  Kathmandu  80000
3      Maya  Kathmandu  85000
9     Kiran    Pokhara  90000
15    Dipak   Lalitpur  82000

In [51]:
# 44. Product and Rating where Rating > 4.5
df.loc[
    df["Rating"] > 4.5,
    ["Product", "Rating"]
]

   Product  Rating
3   Laptop     4.8
8    Phone     4.6
9   Laptop     4.7
15  Laptop     4.9

In [52]:
# 45. Customer, Product and Quantity where Quantity > 3
df.loc[
    df["Quantity"] > 3,
    ["Customer", "Product", "Quantity"]
]

   Customer    Product  Quantity
2     Rohan  Headphone         5
5       Anu      Phone         4
6     Suman      Mouse         6
11  Aashish  Headphone         4
12     Puja      Mouse         5
14    Sneha   Keyboard         6
17      Raj      Mouse         7
19   Manish  Headphone         4

In [53]:
# 46. Laptop OR Phone from Kathmandu
df.loc[
    (df["City"] == "Kathmandu") &
    (
        (df["Product"] == "Laptop") |
        (df["Product"] == "Phone")
    )
]

    Order_ID Customer Product     Category       City  Quantity  Price  Rating
0       1001    Aarav  Laptop  Electronics  Kathmandu         2  80000     4.5
3       1004     Maya  Laptop  Electronics  Kathmandu         1  85000     4.8
13      1014   Roshan   Phone  Electronics  Kathmandu         2  51000     4.5

In [54]:
# 47. Electronics AND Price > 40000
df.loc[
    (df["Category"] == "Electronics") &
    (df["Price"] > 40000)
]

    Order_ID Customer Product     Category       City  Quantity  Price  Rating
0       1001    Aarav  Laptop  Electronics  Kathmandu         2  80000     4.5
1       1002     Sita   Phone  Electronics    Pokhara         3  50000     4.2
3       1004     Maya  Laptop  Electronics  Kathmandu         1  85000     4.8
5       1006      Anu   Phone  Electronics    Pokhara         4  48000     4.4
8       1009    Nabin   Phone  Electronics  Bhaktapur         2  52000     4.6
9       1010    Kiran  Laptop  Electronics    Pokhara         1  90000     4.7
13      1014   Roshan   Phone  Electronics  Kathmandu         2  51000     4.5
15      1016    Dipak  Laptop  Electronics   Lalitpur         1  82000     4.9
18      1019    Nisha   Phone  Electronics    Pokhara         2  49000     4.3

In [55]:
# 48. Accessories AND Rating > 4.0
#     AND Quantity > 3
df.loc[
    (df["Category"] == "Accessories") &
    (df["Rating"] > 4.0) &
    (df["Quantity"] > 3)
]

,Order_ID,Customer,Product,Category,City,Quantity,Price,Rating
6,1007,Suman,Mouse,Accessories,Kathmandu,6,1200,4.1
12,1013,Puja,Mouse,Accessories,Bhaktapur,5,1000,4.2
14,1015,Sneha,Keyboard,Accessories,Pokhara,6,2800,4.1
17,1018,Raj,Mouse,Accessories,Bhaktapur,7,1100,4.4

In [56]:
# 49. Display only Customer and Product
#     Price > 50000 AND Rating > 4.5
df.loc[
    (df["Price"] > 50000) &
    (df["Rating"] > 4.5),
    ["Customer", "Product"]
]

   Customer Product
3      Maya  Laptop
8     Nabin   Phone
9     Kiran  Laptop
15    Dipak  Laptop

In [57]:
# 50. Kathmandu OR Pokhara
#     AND Price > 40000
df.loc[
    (
        (df["City"] == "Kathmandu") |
        (df["City"] == "Pokhara")
    ) &
    (df["Price"] > 40000)
]

    Order_ID Customer Product     Category       City  Quantity  Price  Rating
0       1001    Aarav  Laptop  Electronics  Kathmandu         2  80000     4.5
1       1002     Sita   Phone  Electronics    Pokhara         3  50000     4.2
3       1004     Maya  Laptop  Electronics  Kathmandu         1  85000     4.8
5       1006      Anu   Phone  Electronics    Pokhara         4  48000     4.4
9       1010    Kiran  Laptop  Electronics    Pokhara         1  90000     4.7
13      1014   Roshan   Phone  Electronics  Kathmandu         2  51000     4.5
18      1019    Nisha   Phone  Electronics    Pokhara         2  49000     4.3